# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: galaxy.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cgalaxy.proto\x12\x05\x44\x61y06\"%\n\x13GalacticCoordinates\x12\x0e\n\x06\x63oords\x18\x01 \x03(\x02\"\xc1\x03\n\x04Ship\x12,\n\talignment\x18\x01 \x01(\x0e\x32\x19.Day06.Ship.AlignmentType\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06length\x18\x03 \x01(\x02\x12(\n\nship_class\x18\x04 \x01(\x0e\x32\x14.Day06.Ship.ShipType\x12\x11\n\tcrew_size\x18\x05 \x01(\x05\x12\r\n\x05\x61rmed\x18\x06 \x01(\x08\x12%\n\x08officers\x18\x07 \x03(\x0b\x32\x13.Day06.Ship.Officer\x1as\n\x07Officer\x12\x17\n\nfirst_name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x16\n\tlast_name\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x11\n\x04rank\x18\x03 \x01(\tH\x02\x88\x01\x01\x42\r\n\x0b_first_nameB\x0c\n\n_last_nameB\x07\n\x05_rank\"$\n\rAlignmentType\x12\x08\n\x04\x41lly\x10\x00\x12\t\n\x05\x45nemy\x10\x01\"_\n\x08ShipType\x12\x0c\n\x08\x43orvette\x10\x00\x12\x0b\n\x07\x46rigate\x10\x01\x12\x0b\n\x07\x43ruiser\x10\x02\x12\r\n\tDestroyer\x10\x03\x12\x0b\n\x07\x43\x61rrier\x10\x04\x12\x0f\n\x0b\x44readnought\x10\x05\x32I\n\rGalaxyService\x12\x38\n\tget_ships\x12\x1a.Day06.GalacticCoordinates\x1a\x0b.Day06.Ship\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'galaxy_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GALACTICCOORDINATES']._serialized_start=23
  _globals['_GALACTICCOORDINATES']._serialized_end=60
  _globals['_SHIP']._serialized_start=63
  _globals['_SHIP']._serialized_end=512
  _globals['_SHIP_OFFICER']._serialized_start=262
  _globals['_SHIP_OFFICER']._serialized_end=377
  _globals['_SHIP_ALIGNMENTTYPE']._serialized_start=379
  _globals['_SHIP_ALIGNMENTTYPE']._serialized_end=415
  _globals['_SHIP_SHIPTYPE']._serialized_start=417
  _globals['_SHIP_SHIPTYPE']._serialized_end=512
  _globals['_GALAXYSERVICE']._serialized_start=514
  _globals['_GALAXYSERVICE']._serialized_end=587
# @@protoc_insertion_point(module_scope)
